In [ ]:
#토큰화 실습
import tensorflow as tf
import keras
import gensim
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer
from tensorflow.keras.preprocessing.text import text_to_word_sequence

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
#word_tokenize 사용
print('단어 토큰화1 :',word_tokenize("Don't be fooled by the dark sounding name, Mr Jone's Orphanage is as cheery as cheery goes for a pastry shop. "))

단어 토큰화1 : ['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [ ]:
#WordPunctTokenizer 사용
#WordPunctTokenizer :  구두점을 별도로 분류하는 특징
print('단어 토큰화2 :',WordPunctTokenizer().tokenize("Don't be fooled by the dark sounding name, Mr Jone's Orphanage is as cheery as cheery goes for a pastry shop. "))

단어 토큰화2 : ['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [ ]:
#Keras -> text_to_word_sequence
#text_to_word_sequence : 기본적으로 모든 알파벳을 소문자로 바꾸면서 마침표나 컴마, 느낌표등의 구두점을 제거. but don't나 Jone's와 같은 경우 아포스트로피를 보존.
print('단어 토큰화3 :',text_to_word_sequence("Don't be fooled by the dark sounding name, Mr Jone's Orphanage is as cheery as cheery goes for a pastry shop. "))

단어 토큰화3 : ["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


In [ ]:
## 표준 토큰화 예제
#토큰화 방법 중 -> Penn Treebank Tokenization 규칙
#규칙1. 하이푼으로 구성된 단어는 하나로 유지
#규칙2. doesn't와 같이 아포스트로피로 '접어'가 함께하는 단어는 분리


from nltk.tokenize import TreebankWordTokenizer

tokenizer = TreebankWordTokenizer()

text="Starting a home-based restaurant may be an ideal. it doesn't have a food chain or restaurant of their own."
print('트리뱅크 워드토크나이저 :',tokenizer.tokenize(text))


트리뱅크 워드토크나이저 : ['Starting', 'a', 'home-based', 'restaurant', 'may', 'be', 'an', 'ideal.', 'it', 'does', "n't", 'have', 'a', 'food', 'chain', 'or', 'restaurant', 'of', 'their', 'own', '.']


In [ ]:
##실습
#His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to make sure no one was near.

#영어 문장의 토큰화를 수행하는 sent_tokenize

from nltk.tokenize import sent_tokenize

text = "His barber kept his word. But keeping such a huge secret to himself was \
driving him crazy. Finally, the barber went up a mountain and almost to the edge \
of a cliff. He dug a hole in the midst of some reeds. He looked about, to make \
sure no one was near."

print('문장 토큰화1 : ',sent_tokenize(text))


문장 토큰화1 :  ['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to make sure no one was near.']


In [ ]:
#문장 중간에 마침표가 다수 나오는 경우
#ex) I am actively looking for Ph.D. students. and you are a Ph.D student.

text="I am actively looking for Ph.D. students. and you are a Ph.D student."
print('문장 토큰화 2:',sent_tokenize(text))

문장 토큰화 2: ['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']


In [ ]:
#한국어 문장 토큰화 kss (Korean Sentence Splitter)
#딥 러닝 자연어 처리가 재미있기는 합니다. 그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다. 이제 해보면 알걸요?

!pip install kss
import kss

text = '딥 러닝 자연어 처리가 재미있기는 합니다. 그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다. 이제 해보면 알걸요?'
print('한국어 문장 토큰화 :' , kss.split_sentences(text))

한국어 문장 토큰화 : ['딥 러닝 자연어 처리가 재미있기는 합니다.', '그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다.', '이제 해보면 알걸요?']


In [ ]:
## NLTK dhk KoNLPy를 이용한 영어, 한국어 토큰화 실습


#NLTK
#NLTK에서는 Penn Treebank POS Tags라는 기준을 사용하여 품사를 태깅함.
import nltk
nltk.download('averaged_perceptron_tagger')
from nltk.tokenize import word_tokenize
from nltk.tag import pos_tag

text = 'I am actively looking for Ph.D. students. and you are a Ph.D. student.'
tokenized_sentence=word_tokenize(text)

print('단어 토큰화 :', tokenized_sentence)
print('품사 태깅 :' , pos_tag(tokenized_sentence))

#PRP 인칭대명사
#VBP 동사
#RB 부사
#VBG 현재부사
#IN 전치사
#NNP 고유명사
#NNS 복수형 명사
#CC 접속사
#DT 관사

단어 토큰화 : ['I', 'am', 'actively', 'looking', 'for', 'Ph.D.', 'students', '.', 'and', 'you', 'are', 'a', 'Ph.D.', 'student', '.']
품사 태깅 : [('I', 'PRP'), ('am', 'VBP'), ('actively', 'RB'), ('looking', 'VBG'), ('for', 'IN'), ('Ph.D.', 'NNP'), ('students', 'NNS'), ('.', '.'), ('and', 'CC'), ('you', 'PRP'), ('are', 'VBP'), ('a', 'DT'), ('Ph.D.', 'NNP'), ('student', 'NN'), ('.', '.')]


[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [ ]:
#한국어 형태소 토큰화 (morpheme tokenization)
#KoNLPy (코엔엘피파이) 패키지 이용
#형태소 분석기 Okt, 꼬꼬마 사용

!pip install konlpy
from konlpy.tag import Okt
from konlpy.tag import Kkma

In [ ]:
#konlpy 메서드
#1) morphs : 형태소 추출
#2) pos : 품사 태깅
#3) nouns : 명사 추출

In [ ]:
#Okt 형태소 분석기 이용
okt = Okt()

print('OKT 형태소 분석:',okt.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('OKT 품사 태킹:',okt.pos("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('OKT 명사 추출 :',okt.nouns("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

OKT 형태소 분석: ['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요']
OKT 품사 태킹: [('열심히', 'Adverb'), ('코딩', 'Noun'), ('한', 'Josa'), ('당신', 'Noun'), (',', 'Punctuation'), ('연휴', 'Noun'), ('에는', 'Josa'), ('여행', 'Noun'), ('을', 'Josa'), ('가봐요', 'Verb')]
OKT 명사 추출 : ['코딩', '당신', '연휴', '여행']


In [ ]:
#꼬꼬마 형태소 분석기 이용
kkma =Kkma()

print('꼬꼬마 형태소 분석:',kkma.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('꼬꼬마 품사  태깅:',kkma.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))
print('꼬꼬마 명사 추출:,',kkma.nouns("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

꼬꼬마 형태소 분석: ['열심히', '코딩', '하', 'ㄴ', '당신', ',', '연휴', '에', '는', '여행', '을', '가보', '아요']
꼬꼬마 품사  태깅: ['열심히', '코딩', '하', 'ㄴ', '당신', ',', '연휴', '에', '는', '여행', '을', '가보', '아요']
꼬꼬마 명사 추출:, ['코딩', '당신', '연휴', '여행']


In [ ]:
#NLTK 표제어 추출
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']

print('표제어 추출 전 :',words)
print('표제어 추출 후 :',[lemmatizer.lemmatize(word) for word in words])

표제어 추출 전 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
표제어 추출 후 : ['policy', 'doing', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']


[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [ ]:
#어간 추출 (Stemming)
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

stemmer = PorterStemmer()

sentence="This was not the map we found in Billy Bones's chest, but an accurate \
copy, complete in all things--names and heights and soundings--with the single \
exception of the red crosses and the written notes."

print('어간 추출 전 :', tokenized_sentence)
print('어간 추출 후 :',[stemmer.stem(word) for word in tokenized_sentence])

어간 추출 전 : ['I', 'am', 'actively', 'looking', 'for', 'Ph.D.', 'students', '.', 'and', 'you', 'are', 'a', 'Ph.D.', 'student', '.']
어간 추출 후 : ['i', 'am', 'activ', 'look', 'for', 'ph.d.', 'student', '.', 'and', 'you', 'are', 'a', 'ph.d.', 'student', '.']


In [ ]:
#Lancaster_stemmer 알고리즘
#Porter vs LancasterStemmer
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer

porter_stemmer = PorterStemmer()
lancaster_stemmer = LancasterStemmer()

words =['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']

print('어간 추출 전',words)
print('PorterStemmer 어간 추출 후:',[porter_stemmer.stem(w) for w in words])
print('LancasterStemmer 어간 추출 후 :',[lancaster_stemmer.stem(w) for w in words])

어간 추출 전 ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
PorterStemmer 어간 추출 후: ['polici', 'do', 'organ', 'have', 'go', 'love', 'live', 'fli', 'die', 'watch', 'ha', 'start']
LancasterStemmer 어간 추출 후 : ['policy', 'doing', 'org', 'hav', 'going', 'lov', 'liv', 'fly', 'die', 'watch', 'has', 'start']


In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from konlpy.tag import Okt

In [ ]:
## 2-4 불용어 (Stopword)
!pip import nltk
nltk.download('stopwords')
#NLTK에서 불용어 확인하기
stop_words_list=stopwords.words('english')
print('불용어 개수:',len(stop_words_list))
print('불용어 10개 출력 :',stop_words_list[:10])

ERROR: unknown command "import"
불용어 개수: 179
불용어 10개 출력 : ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
#NLTK를 통해서 불용어 제거하기
example="Family is not an important thing. It's everything."
stop_words=set(stopwords.words('english'))

word_tokens=word_tokenize(example)

result=[]
for word in word_tokens:
  if word not in stop_words:
    result.append(word)

print('불용어 제거 전:',word_tokens)
print('불용어 제거 후:',result)

불용어 제거 전: ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
불용어 제거 후: ['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


In [ ]:
#한국어에서 불용어 제거하기
okt = Okt()

example="고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."
#직접 불용어 정의
stop_words="를 아무렇게나 구 우려 고 안 돼 같은 게 구울 때 는"

stop_words=set(stop_words.split(' '))
word_tokens=okt.morphs(example)

result=[word for word in word_tokens if not word in stop_words]

print('불용어 제거 전:',word_tokens)
print('불용어 제거 후:',result)

불용어 제거 전: ['고기', '를', '아무렇게나', '구', '우려', '고', '하면', '안', '돼', '.', '고기', '라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살', '을', '구울', '때', '는', '중요한', '게', '있지', '.']
불용어 제거 후: ['고기', '하면', '.', '고기', '라고', '다', '아니거든', '.', '예컨대', '삼겹살', '을', '중요한', '있지', '.']


In [ ]:
#정규 표현식
import re

In [ ]:
# . 기호
#.은 한 개의 임의의 문자
r = re.compile("a.c")
r.search("kkk") #아무런 결과도 출력되지 않음


In [ ]:
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
# ? 기호 : ?앞의 문자가 존재할 수도 있고 존재하지 않을 수도 있는 경우
r=re.compile("ab?c")
r.search("abbc") #아무런 결과도 출력되지 않는다.

In [ ]:
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
r.search("ac")

<re.Match object; span=(0, 2), match='ac'>

In [ ]:
# * 기호 : 바로 앞의 문자가 0개 이상일 경우 (존재하지 않을 수도 있고, 여러 개일 수도 있음.)
r=re.compile("ab*c")
r.search("a")

In [ ]:
r.search("ac")

<re.Match object; span=(0, 2), match='ac'>

In [ ]:
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
r.search("abbbbc")

<re.Match object; span=(0, 6), match='abbbbc'>

In [ ]:
# + 기호 : 앞의 문자가 최소 1개 이상이어야 함
r=re.compile("ab+c")

In [ ]:
r.search("ac")

In [ ]:
r.search("abc")

<re.Match object; span=(0, 3), match='abc'>

In [ ]:
# ^ 기호: 시작하는 문자열 지정

r=re.compile("^ab")

r.search("abz")

<re.Match object; span=(0, 2), match='ab'>

In [ ]:
# 정수 인코딩 Integer Encoding
#dictionary 사용하기
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [ ]:
raw_text="A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [ ]:
#문장 토큰화
sentences = sent_tokenize(raw_text)
print(sentences)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [ ]:
vocab = {}
preprocessed_sentences = []
stop_words =set(stopwords.words('english'))

for sentence in sentences:
  # 단어 토큰화
  tokenized_sentence = word_tokenize(sentence)
  result=[]

  for word in tokenized_sentence:
    word = word.lower() #모든 단어를 소문자화하여 단어의 개수를 줄임
    if word not in stop_words: #불용어 제거
      if len(word) > 2: #단어 길이 2이하인 경우에 단어 제거
        result.append(word)
        if word not in vocab:
          vocab[word]=0
        vocab[word]+=1
  preprocessed_sentences.append(result)
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [ ]:
print('단어집합:',vocab)

단어집합: {'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}


In [ ]:
#'barber'라는 단어의 빈도수 출력
print(vocab['barber'])

8


In [ ]:
#빈도수 내림차순으로 정렬
vocab_sorted=sorted(vocab.items(),key=lambda x:x[1], reverse=True)
print(vocab_sorted)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [ ]:
#높은 빈도수를 가진 단어일수록 낮은 정수를 부여함.
word_to_index={}
i=0
for (word,frequency) in vocab_sorted:
  if frequency > 1 : #빈도수가 작은 단어는 제외
    i = i+1
    word_to_index[word]=i

print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [ ]:
vocab_size=5

#인덱스가 5초과인 단어 제거
words_frequency = [word for word, index in word_to_index.items() if index >= vocab_size +1]

#해당 단어에 대한 인덱스 정보를 삭제
for w in words_frequency:
  del word_to_index[w]
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [ ]:
#Out-Of-Vocabualry = OOV : 단어 집합에 존재하지 않는 단어들이 생기는 상황 -> 'OOV'의 인덱스로 인코딩해주기
word_to_index['OOV'] = len(word_to_index) +1
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}


In [ ]:
#word_to_index를 사용하여 sentences의 모든 단어들을 맵핑되는 정수로 인코딩
encoded_sentences = []
for sentence in preprocessed_sentences:
  encoded_sentence = []
  for word in sentence:
    try:
      #단어 집합에 있는 단어라면 해당 단어의 정수를 리턴.
      encoded_sentence.append(word_to_index[word])
    except KeyError:
      #만약 단어 집합에 없는 단어라면 'OOV'의 정수를 리턴.
      encoded_sentence.append(word_to_index['OOV'])
  encoded_sentences.append(encoded_sentence)
print(encoded_sentences)

[[1, 5], [1, 6, 5], [1, 3, 5], [6, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [6, 6, 3, 2, 6, 1, 6], [1, 6, 3, 6]]


In [ ]:
#Counter 사용하기
from collections import Counter
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [ ]:
#words = np.hstach(preprocessed_sentences)으로도 수행가능.
all_words_list=sum(preprocessed_sentences,[])
print(all_words_list)

['barber', 'person', 'barber', 'good', 'person', 'barber', 'huge', 'person', 'knew', 'secret', 'secret', 'kept', 'huge', 'secret', 'huge', 'secret', 'barber', 'kept', 'word', 'barber', 'kept', 'word', 'barber', 'kept', 'secret', 'keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy', 'barber', 'went', 'huge', 'mountain']


In [ ]:
#파이썬의 Counter모듈을 이요하여 단어의 빈도수 카운트
vocab=Counter(all_words_list)
print(vocab)

Counter({'barber': 8, 'secret': 6, 'huge': 5, 'kept': 4, 'person': 3, 'word': 2, 'keeping': 2, 'good': 1, 'knew': 1, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1})


In [ ]:
print(vocab['barber'])

8


In [ ]:
vocab_size=5
vocab=vocab.most_common(vocab_size) #등장 빈도수가 높은 상위 5개의 단어 저장
vocab

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [ ]:
#높은 빈도수를 가진 단어일수록 낮은 정수 인덱스 부여
word_to_index={}
i=0
for (word,frequency) in vocab:
  i=i+1
  word_to_index[word] = i

print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [ ]:
#NLTK의 FreqDist 사용하기
from nltk import FreqDist
import numpy as np

In [ ]:
#np.hstack으로 문장 구분을 제거
vocab=FreqDist(np.hstack(preprocessed_sentences))

In [ ]:
print(vocab["barber"]) #'barber'라는 단어의 빈도수 출력

8


In [ ]:
vocab_size=5
vocab=vocab.most_common(vocab_size) #등장 빈도수가 높은 상위 5개 단어만 저장
print(vocab)

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]


In [ ]:
#enumerate() 사용
word_to_index={word[0] : index + 1 for index, word in enumerate(vocab)}
print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}


In [ ]:
#enumerate 이해하기
test_input = ['a','b','c','d','e']
for index, value in enumerate(test_input): #입력의 순서대로 0부터 인덱스를 부여함.
  print("value: {}, index:{}".format(value,index))

value: a, index:0
value: b, index:1
value: c, index:2
value: d, index:3
value: e, index:4


In [ ]:
#Keras의 텍스트 전처리
#Keras는 기본적인 전처리를 위한 도구들을 제공

from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
preprocessed_sentences = [['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

In [ ]:
tokenizer = Tokenizer()

In [ ]:
#fit_on_texts() 안에 코퍼스를 입력으로 하면 빈도수를 기준으로 단어 집합을 생성.
tokenizer.fit_on_texts(preprocessed_sentences)

In [ ]:
#word_index : 각 단어에 인덱스가 어떻게 부여되었는지 확인
print(tokenizer.word_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [ ]:
#word_counts : 각 단어가 카운트를 수행하였을 때 몇개였는지 확인
print(tokenizer.word_counts)

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [ ]:
#texts_to_sequences() : 입력으로 들어온 코퍼스에 대해서 각 단어를 이미 정해진 인덱스로 변환
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [ ]:
#tokenizer = Tokenizer(num_words=숫자) : 빈도수가 높은 상위 몇개의 단어만 사용하겠다고 사용자 지정해주기
vocab_size=5
tokenizer=Tokenizer(num_words=vocab_size+1) #상위 5개 단어만 사용
tokenizer.fit_on_texts(preprocessed_sentences)

In [ ]:
print(tokenizer.word_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [ ]:
print(tokenizer.word_counts)

OrderedDict([('barber', 8), ('person', 3), ('good', 1), ('huge', 5), ('knew', 1), ('secret', 6), ('kept', 4), ('word', 2), ('keeping', 2), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)])


In [ ]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))

[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [ ]:
tokenzier=Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences)

In [ ]:
vocab_size=5
words_frequency=[word for word,index in tokenizer.word_index.items() if index >= vocab_size +1]


#인덱스가 5초과인 단어 제거
for word in words_frequency:
  del tokenizer.word_index[word] #해당 단어에 대한 인덱스 정보를 삭제
  del tokenizer.word_counts[word] #해당 단어에 대한 카운트 정보를 삭제

print(tokenizer.word_index)
print(tokenizer.word_counts)
print(tokenizer.texts_to_sequences(preprocessed_sentences))

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}
OrderedDict([('barber', 16), ('person', 6), ('huge', 10), ('secret', 12), ('kept', 8)])
[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [ ]:
# 숫자 0과 OOV를 고려해서 단어 집합의 크기는 +2
vocab_size=5
tokenizer = Tokenizer (num_words=vocab_size+2 , oov_token='OOV')
tokenizer.fit_on_texts(preprocessed_sentences)

In [ ]:
# print('단어 OOV의 인덱스 : {}'.format(tokenzier.word_index['OOV'])) #error

In [ ]:
print(tokenizer.texts_to_sequences(preprocessed_sentences))
#빈도수 상위 5개의 단어는 2~6까지의 인덱스를 가지고, 그 외 단어 집합에 없는 'good'과 같은 단어들은 전부 'OOV'의 인덱스인 1로 인코딩 됨

[[2, 6], [2, 1, 6], [2, 4, 6], [1, 3], [3, 5, 4, 3], [4, 3], [2, 5, 1], [2, 5, 1], [2, 5, 3], [1, 1, 4, 3, 1, 2, 1], [2, 1, 4, 1]]


In [ ]:
## 패딩
#1. numpy로 패딩하기
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
preprocessed_sentences =[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]

In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(preprocessed_sentences) #빈도수를 기준으로 단어 집합을 생성
encoded=tokenizer.texts_to_sequences(preprocessed_sentences) #입력으로 들어온 코퍼스에 대해서 각 단어를 이미 정해진 인덱스로 변환
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [ ]:
#동일한 길이로 맞춰주기 위해서 가장 길이가 긴 문장의 길이 계산
max_len =max(len(item) for item in encoded)
print('최대 길이:',max_len)

최대 길이: 7


In [ ]:
#모든 문장의 길이를 같에 맞춰줌
#가상의 단어 'PAD'이용 -> 0번 단어로 정의
#길이가 7보다 짧은 문장에 0을 채워 길이를 7로 맞춰주는 과정

for sentence in encoded:
  while len(sentence) < max_len:
    sentence.append(0)

padded_np =np.array(encoded)
padded_np

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [ ]:
#케라스 전처리 도구로 패딩하기
#keras -> pad_sequences

from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
#encoded값 패딩 전 값으로 돌려주기
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [ ]:
padded=pad_sequences(encoded)
padded

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]], dtype=int32)

In [ ]:
#위의 계산결과가 numpy와 다른이유 : pad_sequences는 문서의 앞을 0으로 채움.
#뒤로 채우고 싶을 경우 padding = 'post'

padded=pad_sequences(encoded,padding='post')
padded

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

In [ ]:
#항상 가장 긴 길이의 문장으로 길이를 맞춰줄 필요 X
#길이에 제한을 두고 padding가능
#maxlen 인자로 정수를 할당
padded=pad_sequences(encoded,padding='post',maxlen=5)
padded

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0]], dtype=int32)

In [ ]:
#maxlen보다 길이가 길었던 문장인 경우 앞부분의 데이터가 손실됨
#이때 뒤의 단어가 삭제되도록 하고 싶다면 truncating='post

padded=pad_sequences(encoded,padding='post',truncating='post',maxlen=5)
padded

array([[ 1,  5,  0,  0,  0],
       [ 1,  8,  5,  0,  0],
       [ 1,  3,  5,  0,  0],
       [ 9,  2,  0,  0,  0],
       [ 2,  4,  3,  2,  0],
       [ 3,  2,  0,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  6,  0,  0],
       [ 1,  4,  2,  0,  0],
       [ 7,  7,  3,  2, 10],
       [ 1, 12,  3, 13,  0]], dtype=int32)

In [ ]:
#0이 아닌 다른 수로 패딩하고 싶을 경우 겹치지 않도록 단어 집합의 크기에 +1한 크기로 사용해보기
last_value = len(tokenizer.word_index) +1 #단어 집합의 크기보다 1 큰 숫자를 사용
print(last_value)

14


In [ ]:
padded=pad_sequences(encoded,padding='post',value=last_value)
padded

array([[ 1,  5, 14, 14, 14, 14, 14],
       [ 1,  8,  5, 14, 14, 14, 14],
       [ 1,  3,  5, 14, 14, 14, 14],
       [ 9,  2, 14, 14, 14, 14, 14],
       [ 2,  4,  3,  2, 14, 14, 14],
       [ 3,  2, 14, 14, 14, 14, 14],
       [ 1,  4,  6, 14, 14, 14, 14],
       [ 1,  4,  6, 14, 14, 14, 14],
       [ 1,  4,  2, 14, 14, 14, 14],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13, 14, 14, 14]], dtype=int32)

In [ ]:
#원-핫 인코딩
#한국어 문장을 예제로 원-핫 벡터 생성
#문장 : 나는 자연어 처리를 배운다


# step1. Okt 형태소 분석기이용하여 토큰화
from konlpy.tag import Okt

okt=Okt()
tokens =okt.morphs("나는 자연어 처리를 배운다")
print(tokens)

['나', '는', '자연어', '처리', '를', '배운다']


In [ ]:
#빈도수를 순으로 단어를 정렬하여 정수를 부여하는 경우가 많음
word_to_index={word : index for index, word in enumerate(tokens)}
print('단어집합:',word_to_index)

단어집합: {'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}


In [ ]:
#토큰을 입력하면 해당 토큰에 대한 원-핫 벡터를 만들어 내는 함수
def one_hot_encoding(word,word_to_index):
  one_hot_vector=[0]*(len(word_to_index))
  index=word_to_index[word]
  one_hot_vector[index]=1
  return one_hot_vector

In [ ]:
#'자연어'라는 단어의 원-핫 벡터 생성
one_hot_encoding("자연어",word_to_index)

[0, 0, 1, 0, 0, 0]

In [ ]:
#Keras를 이용한 원-핫 인코딩
#Keras -> to_categorical()

text='나랑 점심 먹으로 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야'

#토크나이저를 이용한 정수인코딩
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

text='나랑 점심 먹으로 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야'

tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
print('단어집합:',tokenizer.word_index)

단어집합: {'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으로': 5, '메뉴는': 6, '최고야': 7}


In [ ]:
#위와같은 단어집합를 정수 시퀀스로 변환하기
sub_text="점심 먹으러 갈래 메뉴는 햄버거 최고야"
encoded=tokenizer.texts_to_sequences([sub_text])[0]
print(encoded)

[2, 1, 6, 3, 7]


In [ ]:
#keras를 이용한 one-hot encoding-> to_categorical()

one_hot=to_categorical(encoded)
print(one_hot)

[[0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
##2-9데이터의 분리
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
#지도학습 (Supervised Learning)

#X와 y분리하기
#1) zip함수를 이용하여 분리하기
#zip : 동일한 개수를 가지는 시퀀스 자료형에서 각 순서에 등장하는 원소들끼리 묶어주는 역할

X,y=zip(['a',1],['b',2],['c',3])
print('X데이터:',X)
print('y데이터:',y)

X데이터: ('a', 'b', 'c')
y데이터: (1, 2, 3)


In [ ]:
#리스트의 리스트 또는 행렬 또는 뒤어서 배울 개념인 2D텐서.
sequences=[['a',1],['b',2],['c',3]]
X,y=zip(*sequences)
print('X데이터:',X)
print('y데이터:',y)

X데이터: ('a', 'b', 'c')
y데이터: (1, 2, 3)


In [ ]:
#데이터프레임을 이용하여 분리하기
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

df=pd.DataFrame(values,columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [ ]:
X=df['메일 본문']
y=df['스팸 메일 유무']

In [ ]:
print('X데이터:',X.to_list())
print('y데이터:',y.to_list())

X데이터: ['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
y데이터: [1, 0, 0, 1]


In [ ]:
#Numpy를 이용하여 분리하기
np_array=np.arange(0,16).reshape((4,4))
print('전체 데이터:')
print(np_array)

전체 데이터:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
#마지막 열을 제외하고 X데이터에 저장, 마지막 열만을 y데이터에 저장
X = np_array[:,:3]
y=np_array[:,3]

print('X데이터:')
print(X)
print('y데이터 :',y)

X데이터:
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y데이터 : [ 3  7 11 15]


In [ ]:
#3.테스트 데이터 분리하기
#1) 사이킷 런을 이용하여 분리하기
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1234)

In [ ]:
# 임의로 X와 y 데이터를 생성
X, y = np.arange(10).reshape((5, 2)), range(5)

print('X 전체 데이터 :')
print(X)
print('y 전체 데이터 :')
print(list(y))

X 전체 데이터 :
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y 전체 데이터 :
[0, 1, 2, 3, 4]


In [ ]:
# 7:3의 비율로 훈련 데이터와 테스트 데이터 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)


In [ ]:
print('X 훈련 데이터 :')
print(X_train)
print('X 테스트 데이터 :')
print(X_test)

X 훈련 데이터 :
[[2 3]
 [4 5]
 [6 7]]
X 테스트 데이터 :
[[8 9]
 [0 1]]


In [ ]:
print('y 훈련 데이터 :')
print(y_train)
print('y 테스트 데이터 :')
print(y_test)


y 훈련 데이터 :
[1, 2, 3]
y 테스트 데이터 :
[4, 0]


In [ ]:
# 실습을 위해 임의로 X와 y가 이미 분리 된 데이터를 생성
X, y = np.arange(0,24).reshape((12,2)), range(12)

print('X 전체 데이터 :')
print(X)
print('y 전체 데이터 :')
print(list(y))


X 전체 데이터 :
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
y 전체 데이터 :
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [ ]:
num_of_train = int(len(X) * 0.8) # 데이터의 전체 길이의 80%에 해당하는 길이값을 구한다.
num_of_test = int(len(X) - num_of_train) # 전체 길이에서 80%에 해당하는 길이를 뺀다.
print('훈련 데이터의 크기 :',num_of_train)
print('테스트 데이터의 크기 :',num_of_test)


훈련 데이터의 크기 : 9
테스트 데이터의 크기 : 3


In [ ]:
X_test = X[num_of_train:] # 전체 데이터 중에서 20%만큼 뒤의 데이터 저장
y_test = y[num_of_train:] # 전체 데이터 중에서 20%만큼 뒤의 데이터 저장
X_train = X[:num_of_train] # 전체 데이터 중에서 80%만큼 앞의 데이터 저장
y_train = y[:num_of_train] # 전체 데이터 중에서 80%만큼 앞의 데이터 저장


In [ ]:
print('X 테스트 데이터 :')
print(X_test)
print('y 테스트 데이터 :')
print(list(y_test))


X 테스트 데이터 :
[[18 19]
 [20 21]
 [22 23]]
y 테스트 데이터 :
[9, 10, 11]


In [ ]:
###2-10 한국어 전처리 패키지 (Text Preprocessing Tools for Korean Text) -> KSS
#1. PyKoSpacing

!pip install git+https://github.com/haven-jeon/PyKoSpacing.git


  Cloning https://github.com/haven-jeon/PyKoSpacing.git to /tmp/pip-req-build-9sr80_22
  Running command git clone --filter=blob:none --quiet https://github.com/haven-jeon/PyKoSpacing.git /tmp/pip-req-build-9sr80_22
  Resolved https://github.com/haven-jeon/PyKoSpacing.git to commit d1e2f93759b1bcc74b6aaa345a62c08701e5546e
  Preparing metadata (setup.py) ... done
  Using cached tensorflow-2.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511.8 MB)
  Using cached h5py-3.1.0.tar.gz (371 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... canceled
ERROR: Operation cancelled by user


In [ ]:
sent = '김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.'


In [ ]:
#띄어쓰기가 없는 문장 임의로 만들기
new_sent=sent.replace(" ",'')
print(new_sent)

김철수는극중두인격의사나이이광수역을맡았다.철수는한국유일의태권도전승자를가리는결전의날을앞두고10년간함께훈련한사형인유연재(김광수분)를찾으러속세로내려온인물이다.


In [ ]:
#pykospacing의 입력으로 원 문장과 비교
from pykospacing import Spacing
spacing = Spacing()
kospacing_sent = spacing(new_sent)

print(sent)
print(kospacing_sent)


ModuleNotFoundError: ignored

In [ ]:
pip install --upgrade pip

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 12.6 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2


In [ ]:
pip install -U setuptools

  Obtaining dependency information for setuptools from https://files.pythonhosted.org/packages/4f/ab/0bcfebdfc3bfa8554b2b2c97a555569c4c1ebc74ea288741ea8326c51906/setuptools-68.1.2-py3-none-any.whl.metadata
  Using cached setuptools-68.1.2-py3-none-any.whl.metadata (6.2 kB)
Using cached setuptools-68.1.2-py3-none-any.whl (805 kB)
  Attempting uninstall: setuptools
    Found existing installation: setuptools 67.7.2
    Uninstalling setuptools-67.7.2:
      Successfully uninstalled setuptools-67.7.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.


In [ ]:
##SOYNLP를 이용한 단어 토큰화
!pip install soynlp

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 416.8/416.8 kB 3.2 MB/s eta 0:00:00


In [ ]:
#신조어 문제
from konlpy.tag import Okt
tokenizer=Okt()
print(tokenizer.morphs('에이비식스 이대휘 1월 최애돌 기부 요정'))

['에이', '비식스', '이대', '휘', '1월', '최애', '돌', '기부', '요정']


In [ ]:
#학습하기
import urllib.request
from soynlp import DoublespaceLineCorpus
from soynlp.word import WordExtractor


In [ ]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/lovit/soynlp/master/tutorials/2016-10-20.txt", filename="2016-10-20.txt")


('2016-10-20.txt', <http.client.HTTPMessage at 0x7a93eeae5cc0>)

In [ ]:
#훈련데이터를 다수의 문서로 분리
corpus = DoublespaceLineCorpus("2016-10-20.txt")
len(corpus)

30091

In [ ]:
i=0
for document in corpus:
  if len(document)>0:
    print(document)
    i=i+1
  if i==3:
    break

19  1990  52 1 22
오패산터널 총격전 용의자 검거 서울 연합뉴스 경찰 관계자들이 19일 오후 서울 강북구 오패산 터널 인근에서 사제 총기를 발사해 경찰을 살해한 용의자 성모씨를 검거하고 있다 성씨는 검거 당시 서바이벌 게임에서 쓰는 방탄조끼에 헬멧까지 착용한 상태였다 독자제공 영상 캡처 연합뉴스  서울 연합뉴스 김은경 기자 사제 총기로 경찰을 살해한 범인 성모 46 씨는 주도면밀했다  경찰에 따르면 성씨는 19일 오후 강북경찰서 인근 부동산 업소 밖에서 부동산업자 이모 67 씨가 나오기를 기다렸다 이씨와는 평소에도 말다툼을 자주 한 것으로 알려졌다  이씨가 나와 걷기 시작하자 성씨는 따라가면서 미리 준비해온 사제 총기를 이씨에게 발사했다 총알이 빗나가면서 이씨는 도망갔다 그 빗나간 총알은 지나가던 행인 71 씨의 배를 스쳤다  성씨는 강북서 인근 치킨집까지 이씨 뒤를 쫓으며 실랑이하다 쓰러뜨린 후 총기와 함께 가져온 망치로 이씨 머리를 때렸다  이 과정에서 오후 6시 20분께 강북구 번동 길 위에서 사람들이 싸우고 있다 총소리가 났다 는 등의 신고가 여러건 들어왔다  5분 후에 성씨의 전자발찌가 훼손됐다는 신고가 보호관찰소 시스템을 통해 들어왔다 성범죄자로 전자발찌를 차고 있던 성씨는 부엌칼로 직접 자신의 발찌를 끊었다  용의자 소지 사제총기 2정 서울 연합뉴스 임헌정 기자 서울 시내에서 폭행 용의자가 현장 조사를 벌이던 경찰관에게 사제총기를 발사해 경찰관이 숨졌다 19일 오후 6시28분 강북구 번동에서 둔기로 맞았다 는 폭행 피해 신고가 접수돼 현장에서 조사하던 강북경찰서 번동파출소 소속 김모 54 경위가 폭행 용의자 성모 45 씨가 쏜 사제총기에 맞고 쓰러진 뒤 병원에 옮겨졌으나 숨졌다 사진은 용의자가 소지한 사제총기  신고를 받고 번동파출소에서 김창호 54 경위 등 경찰들이 오후 6시 29분께 현장으로 출동했다 성씨는 그사이 부동산 앞에 놓아뒀던 가방을 챙겨 오패산 쪽으로 도망간 후였다  김 경위는 오패산 터널 입구 오른쪽의 급경사에서 성씨에

In [ ]:
#엔트로피 단어 점수표를 만든느 과정 -> WordExtractor.extract()
word_extractor=WordExtractor()
word_extractor.train(corpus)
word_score_table=word_extractor.extract()

training was done. used memory 2.413 Gb
all cohesion probabilities was computed. # words = 223348
all branching entropies was computed # words = 361598
all accessor variety was computed # words = 361598


In [ ]:
##SOYNLP의 응집확률 (cohension probability)
word_score_table["반포한"].cohesion_forward

0.08838002913645132

In [ ]:
word_score_table['반포한강'].cohesion_forward

0.19841268168224552

In [ ]:
word_score_table['반포한강공원에'].cohesion_forward

0.33492963377557666

In [ ]:
#SOYNLP의 브랜칭 엔트로피 (branching entropy)
word_score_table["디스"].right_branching_entropy

1.6371694761537934

In [ ]:
word_score_table['디스플'].right_branching_entropy

-0.0

In [ ]:
word_score_table['디스플레이'].right_branching_entropy

3.1400392861792916

In [ ]:
#SOYNLP의 tokenizer

from soynlp.tokenizer import LTokenizer

scores={word:score.cohesion_forward for word, score in word_score_table.items()}
l_tokenizer = LTokenizer(scores=scores)
l_tokenizer.tokenize("국제사회와 우리의 노력들로 범죄를 척결하자",flatten=False)

[('국제사회', '와'), ('우리', '의'), ('노력', '들로'), ('범죄', '를'), ('척결', '하자')]

In [ ]:
#최대 점수 토크나이저
#띄어쓰기가 되지 않는 문장에서 점수가 높은 글자 시퀀스를 순차적으로 찾아내는 토크나이저.

from soynlp.tokenizer import MaxScoreTokenizer

maxscore_tokenizer = MaxScoreTokenizer(scores=scores)
maxscore_tokenizer.tokenize("국제사회와우리의노력들로범죄를척결하자")

['국제사회', '와', '우리', '의', '노력', '들로', '범죄', '를', '척결', '하자']

In [ ]:
#SNS나 채팅 데이터의 경우 불필요하게 연속되는 경우 -> 하나로 정규화해줄 필요
from soynlp.normalizer import *

In [ ]:
print(emoticon_normalize('앜ㅋㅋㅋㅋ이영화존잼쓰ㅠㅠㅠㅠㅠ', num_repeats=2))
print(emoticon_normalize('앜ㅋㅋㅋㅋㅋㅋㅋㅋㅋ이영화존잼쓰ㅠㅠㅠㅠ', num_repeats=2))
print(emoticon_normalize('앜ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ이영화존잼쓰ㅠㅠㅠㅠㅠㅠ', num_repeats=2))
print(emoticon_normalize('앜ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ이영화존잼쓰ㅠㅠㅠㅠㅠㅠㅠㅠ', num_repeats=2))


아ㅋㅋ영화존잼쓰ㅠㅠ
아ㅋㅋ영화존잼쓰ㅠㅠ
아ㅋㅋ영화존잼쓰ㅠㅠ
아ㅋㅋ영화존잼쓰ㅠㅠ


In [ ]:
print(repeat_normalize('와하하하하하하하하하핫', num_repeats=2))
print(repeat_normalize('와하하하하하하핫', num_repeats=2))
print(repeat_normalize('와하하하하핫', num_repeats=2))


와하하핫
와하하핫
와하하핫


In [ ]:
#Coustomized KoNLPy
