In [19]:
!pip install konlpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 30.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 465.3/465.3 kB 33.8 MB/s eta 0:00:00


In [41]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

## 1. 토큰화(Tokenization)

### 단어 토큰화
- word_tokenize
- WordPuncTokenizer
- test_to_word_sequence
- Penn Treebank Tokenization

In [5]:
# 필요 라이브러리 import
# word_tokenize, WordPunctTokenizer 사용
from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from nltk.tokenize import TreebankWordTokenizer

<Penn Treebank Tokenization의 규칙>\
규칙 1. 하이푼으로 구성된 단어는 하나로 유지한다.\
규칙 2. doesn't와 같이 아포스트로피로 '접어'가 함께하는 단어는 분리해준다.\
\
word_tokenize와 WordPunctTokenizer가 '를 다르게 전처리 하는 것을 볼 수 있다.\
keras의 text_to_word_sequence는 '를 따로 분리하지는 않지만 lowercase로 바꾸고 있다.


In [11]:
# 단어 토큰화 수행
 # 단어 토큰화 이외에도 의미가 있는 단위로 토큰화 가능

sentence = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."

 # word_tokenize
print('word_tokenize 토큰화:', word_tokenize(sentence))

 # WordPunctTokenizer
print('WordPunctTokenizer 토큰화:', WordPunctTokenizer().tokenize(sentence))

# text_to_word_sequence
print('text_to_word_sequence 토큰화:',text_to_word_sequence(sentence))

# Penn Treebank Tokenization
print('Penn Treebank Tokenization 토큰화:',TreebankWordTokenizer().tokenize(text))

word_tokenize 토큰화: ['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']
WordPunctTokenizer 토큰화: ['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']
text_to_word_sequence 토큰화: ["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']
Penn Treebank Tokenization 토큰화: ['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


### 문장 토큰화
문장별로 끊어서 toenization.\
항상 ".", "!", "?"로 끝난다고 문장인 것은 아니다!
적절히 학습된 tokenizer를 사용하자
- sent_tokenize

In [12]:
from nltk.tokenize import sent_tokenize

text = "His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to make sure no one was near."
print('문장 토큰화1 :',sent_tokenize(text))


문장 토큰화1 : ['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to make sure no one was near.']


In [13]:
# 마침표가 많이 들어가 있다면 어떨까?
text = "I am actively looking for Ph.D. students. and you are a Ph.D student."
print('문장 토큰화2 :',sent_tokenize(text))

문장 토큰화2 : ['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']


중간에 Ph.D라는 용어를 잘 넘기고 문장 별로 분리하고 있다.

### 한국어 토큰화 by okt 와 품사 태깅


### Okt(Open Korea Text)

In [21]:
from konlpy.tag import Okt
okt=Okt()
text = '딥 러닝 자연어 처리가 재미있기는 합니다. 그런데 문제는 영어보다 한국어로 할 때 너무 어렵습니다. 이제 해보면 알걸요?'

# 형태소 추출
print(okt.morphs(text))

# 품사 태깅
print(okt.pos(text))

#  명사 추출
print(okt.nouns(text))

['딥', '러닝', '자연어', '처리', '가', '재미있기는', '합니다', '.', '그런데', '문제', '는', '영어', '보다', '한국어', '로', '할', '때', '너무', '어렵습니다', '.', '이제', '해보면', '알걸', '요', '?']
[('딥', 'Noun'), ('러닝', 'Noun'), ('자연어', 'Noun'), ('처리', 'Noun'), ('가', 'Josa'), ('재미있기는', 'Adjective'), ('합니다', 'Verb'), ('.', 'Punctuation'), ('그런데', 'Conjunction'), ('문제', 'Noun'), ('는', 'Josa'), ('영어', 'Noun'), ('보다', 'Josa'), ('한국어', 'Noun'), ('로', 'Josa'), ('할', 'Verb'), ('때', 'Noun'), ('너무', 'Adverb'), ('어렵습니다', 'Adjective'), ('.', 'Punctuation'), ('이제', 'Noun'), ('해보면', 'Verb'), ('알걸', 'Noun'), ('요', 'Josa'), ('?', 'Punctuation')]
['딥', '러닝', '자연어', '처리', '문제', '영어', '한국어', '때', '이제', '알걸']


### Kkma

In [22]:
from konlpy.tag import Kkma
kkma = Kkma()

# 형태소 추출
print(kkma.morphs(text))

# 품사 태깅
print(kkma.pos(text))

#  명사 추출
print(kkma.nouns(text))

['딥', '러닝', '자연어', '처리', '가', '재미있', '기', '는', '하', 'ㅂ니다', '.', '그러', 'ㄴ', '데', '문제', '는', '영어', '보다', '한국어', '로', '하', 'ㄹ', '때', '너무', '어렵', '습니다', '.', '이제', '해보', '면', '알', 'ㄹ걸요', '?']
[('딥', 'NNG'), ('러닝', 'NNG'), ('자연어', 'NNG'), ('처리', 'NNG'), ('가', 'JKS'), ('재미있', 'VA'), ('기', 'ETN'), ('는', 'JX'), ('하', 'VV'), ('ㅂ니다', 'EFN'), ('.', 'SF'), ('그러', 'VV'), ('ㄴ', 'ETD'), ('데', 'NNB'), ('문제', 'NNG'), ('는', 'JX'), ('영어', 'NNG'), ('보다', 'JKM'), ('한국어', 'NNG'), ('로', 'JKM'), ('하', 'VV'), ('ㄹ', 'ETD'), ('때', 'NNG'), ('너무', 'MAG'), ('어렵', 'VA'), ('습니다', 'EFN'), ('.', 'SF'), ('이제', 'MAG'), ('해보', 'VV'), ('면', 'ECE'), ('알', 'VV'), ('ㄹ걸요', 'EFN'), ('?', 'SF')]
['딥', '러닝', '자연어', '처리', '데', '문제', '영어', '한국어', '때']


## 2. 정제(Cleaning), 정규화(Normalization) with 정규 표현식
- 정제(cleaning) : 갖고 있는 코퍼스로부터 노이즈 데이터를 제거한다.
- 정규화(normalization) : 표현 방법이 다른 단어들을 통합시켜서 같은 단어로 만들어준다.
- 정규 표현식 참고: https://hamait.tistory.com/342
책 보다는 위의 링크가 자주 사용하는 예시와 다양한 문법이 정리되어 있다.

In [23]:
import re
text = "I was wondering if anyone out there could enlighten me on this car."

# 길이가 1~2인 단어들을 정규 표현식을 이용하여 삭제
shortword = re.compile(r'\W*\b\w{1,2}\b')
print(shortword.sub('', text))

 was wondering anyone out there could enlighten this car.


In [24]:
text = "Regular expression : A regular expression, regex or regexp[1] (sometimes called a rational expression)[2][3] is, in theoretical computer science and formal language theory, a sequence of characters that define a search pattern."

# 영어 소문자와 대문자를 제외한 모든 문자를 공백으로 치환
preprocessed_text = re.sub('[^a-zA-Z]', ' ', text)
print(preprocessed_text)

Regular expression   A regular expression  regex or regexp     sometimes called a rational expression        is  in theoretical computer science and formal language theory  a sequence of characters that define a search pattern 


In [30]:
text = "People is in SEOUL Women's  University 2023.     Ph.D Baek's   number is 200. I WANT to go my home"

# 공백 기준으로 split하기, 공백의 개수 상관 없음
print(re.split('\s+', text)  )

# 숫자 찾기
print(re.findall('\d+',text)  )

# 대문자 1문자 가져오기
print(re.findall('[A-Z]',text))

# 대문자 연속 4번 이상 반복하는 글자 가져오기
print(re.findall('[A-Z]{4,}',text))

# 맨 앞 문자가 대문자로 시작. 나머지 뒷 글자는 소문자로 시작하는 단어 찾기
print(re.findall('[A-Z][a-z]+',text))

['People', 'is', 'in', 'SEOUL', "Women's", 'University', '2023.', 'Ph.D', "Baek's", 'number', 'is', '200.', 'I', 'WANT', 'to', 'go', 'my', 'home']
['2023', '200']
['P', 'S', 'E', 'O', 'U', 'L', 'W', 'U', 'P', 'D', 'B', 'I', 'W', 'A', 'N', 'T']
['SEOUL', 'WANT']
['People', 'Women', 'University', 'Ph', 'Baek']


## 3.어간 추출(Stemming) and 표제어 추출(Lemmatization)
목적: 눈으로 봤을 때는 서로 다른 단어들이지만, 하나의 단어로 일반화시킬 수 있다면 하나의 단어로 일반화시켜서 문서 내의 단어 수를 줄이는 것\
 \

- 표제어 추출: 뿌리 단어 찾기\
ex) is, am, are -> be

- 어간 추출: 어간을 추출하는 작업(의미가 있는 부분)\
어간: 용언이 바뀌지 않은 부분, 의미가 바뀌지 않고 고유한 부분\
어미: 접사 등 바뀌는 부분


### 표제어 추출

In [34]:
# 표제어 추출
from nltk.stem import WordNetLemmatizer

# 형태가 적절히 보존됨
lemmatizer = WordNetLemmatizer()

words = ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']

print('표제어 추출 전: ',words)
print('표제어 추출 후: ',[lemmatizer.lemmatize(word) for word in words])

# 단어의 품사에 대한 정보를 제공함으로써 보다 정확한 표제어를 추출 가능
print(lemmatizer.lemmatize('dies', 'v'))
print(lemmatizer.lemmatize('had', 'v'))
print(lemmatizer.lemmatize('flowers', 'n'))

표제어 추출 전:  ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
표제어 추출 후:  ['policy', 'doing', 'organization', 'have', 'going', 'love', 'life', 'fly', 'dy', 'watched', 'ha', 'starting']
die
have
flower


### 어간 추출

<어간 추출 알고리즘 in English>
- 포터 스테머(Poter stemmer)
- 랭커스터 스테머(Lancaster stemmer)\
둘 다 알고리즘이 다르기 때문에 특정 상황에 따라 성능이 갈린다. 적절한 것을 골라서 사용할 것

In [38]:
# 어간 추출 - 스테밍
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
from nltk.tokenize import word_tokenize

stemmer1 = PorterStemmer()
stemmer2 = LancasterStemmer()

# test1
print("Poter Stemmer: ", stemmer1.stem('cooking'), stemmer1.stem('cookery'), stemmer1.stem('cookbooks'))
print('Lancaster Stemmer: ', stemmer2.stem('cooking'), stemmer2.stem('cookery'), stemmer2.stem('cookbooks'))

# test2
words = ['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print('Poter Stemmer: ',[stemmer1.stem(w) for w in words])
print('Lancaster Stemmer: ',[stemmer2.stem(w) for w in words])


Poter Stemmer:  cook cookeri cookbook
Lancaster Stemmer:  cook cookery cookbook
Poter Stemmer:  ['polici', 'do', 'organ', 'have', 'go', 'love', 'live', 'fli', 'die', 'watch', 'ha', 'start']
Lancaster Stemmer:  ['policy', 'doing', 'org', 'hav', 'going', 'lov', 'liv', 'fly', 'die', 'watch', 'has', 'start']


In [37]:
sentence = "This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes."
tokenized_sentence = word_tokenize(sentence)

print('Poter Stemmer: ',[stemmer1.stem(word) for word in tokenized_sentence])
print('Lancaster Stemmer: ',[stemmer2.stem(word) for word in tokenized_sentence])

Poter Stemmer:  ['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']
Lancaster Stemmer:  ['thi', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'bil', 'bon', "'s", 'chest', ',', 'but', 'an', 'acc', 'cop', ',', 'complet', 'in', 'al', 'thing', '--', 'nam', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'exceiv', 'of', 'the', 'red', 'cross', 'and', 'the', 'writ', 'not', '.']


## 4. 불용어

분석 할 때, 의미 없는 단어를 제거하는 과정\
ex) I, my, me, over, 조사, 접미사 등\
user가 직접 지정할 수 있지만 nltk에서 이미 불용어 사전이 존재함

### 불용어 사전

In [44]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from konlpy.tag import Okt

# 영어 불용어 사전 보기
# 불어, 독일어, 그리스어 등 23개 언어 지원, 한국어 미포함 -> konlpy 사용
stop_words_list = stopwords.words('english')
print('불용어 개수 :', len(stop_words_list))
print('불용어 10개 출력 :',stop_words_list[:10])

# 불어 불용어 사전 보기
stop_words_list = stopwords.words('french')
print('불용어 개수 :', len(stop_words_list))
print('불용어 10개 출력 :',stop_words_list[:10])

불용어 개수 : 179
불용어 10개 출력 : ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]
불용어 개수 : 157
불용어 10개 출력 : ['au', 'aux', 'avec', 'ce', 'ces', 'dans', 'de', 'des', 'du', 'elle']


### 불용어 제거 하기

In [45]:
example = "Family is not an important thing. It's everything."
# 영어 불용어 사전 setting
stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(example)

result = []
for word in word_tokens:
    if word not in stop_words:
        result.append(word)

print('불용어 제거 전 :',word_tokens)
print('불용어 제거 후 :',result)

불용어 제거 전 : ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
불용어 제거 후 : ['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


### 한국어 불용어 사전 사용하기

In [47]:
okt = Okt()

example = "집에 가고 싶어요. 보내주세요. 대학원 가기 싫어요. 논문 쓰기 싫어요 살려줘. 자고 싶어요 발표 준비 해야하는데 논문 아직 안 읽었다."
stop_words = "에 대학원 논문"

stop_words = set(stop_words.split(' '))
word_tokens = okt.morphs(example)

result = [word for word in word_tokens if not word in stop_words]

# 논문과 대학원 제거^^
print('불용어 제거 전 :',word_tokens)
print('불용어 제거 후 :',result)

불용어 제거 전 : ['집', '에', '가고', '싶어요', '.', '보내주세요', '.', '대학원', '가기', '싫어요', '.', '논문', '쓰기', '싫어요', '살려줘', '.', '자고', '싶어요', '발표', '준비', '해야하는데', '논문', '아직', '안', '읽었다', '.']
불용어 제거 후 : ['집', '가고', '싶어요', '.', '보내주세요', '.', '가기', '싫어요', '.', '쓰기', '싫어요', '살려줘', '.', '자고', '싶어요', '발표', '준비', '해야하는데', '아직', '안', '읽었다', '.']


## 정수 및 One-hot encoding

문장 토큰화 -> 정수 인코딩 -> (패딩) -> one hot encoding

In [48]:
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

raw_text = "A barber is a person. a barber is good person. \
a barber is huge person. \
he Knew A Secret! The Secret He Kept is huge secret. \
Huge secret. His barber kept his word. \
a barber kept his word. His barber kept his secret. \
But keeping and keeping such a huge secret to himself was driving the barber crazy. \
the barber went up a huge mountain."

# 문장 토큰화
sentences = sent_tokenize(raw_text)
print(sentences)

['A barber is a person.', 'a barber is good person.', 'a barber is huge person.', 'he Knew A Secret!', 'The Secret He Kept is huge secret.', 'Huge secret.', 'His barber kept his word.', 'a barber kept his word.', 'His barber kept his secret.', 'But keeping and keeping such a huge secret to himself was driving the barber crazy.', 'the barber went up a huge mountain.']


In [49]:
vocab = {}
preprocessed_sentences = []
stop_words = set(stopwords.words('english'))

for sentence in sentences:
    # 단어 토큰화
    tokenized_sentence = word_tokenize(sentence)
    result = []

    for word in tokenized_sentence:
       # 모든 단어를 소문자화하여 단어의 개수를 줄인다.
        word = word.lower()
         # 단어 토큰화 된 결과에 대해서 불용어를 제거한다.
        if word not in stop_words:

          # 단어 길이가 2이하인 경우에 대하여 추가로 단어를 제거한다. 분석적으로 의미 없는 단어일 확률이 높음
            if len(word) > 2:

              # 결과에 불용어 제거된 문장이 담김
                result.append(word)

                # 단어 빈도수를 vocab에 기록
                if word not in vocab:
                    vocab[word] = 0
                vocab[word] += 1
    preprocessed_sentences.append(result)
print(preprocessed_sentences)

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


In [51]:
print(vocab)

# 빈도순 정렬
vocab_sorted = sorted(vocab.items(), key = lambda x:x[1], reverse = True)
print(vocab_sorted)

{'barber': 8, 'person': 3, 'good': 1, 'huge': 5, 'knew': 1, 'secret': 6, 'kept': 4, 'word': 2, 'keeping': 2, 'driving': 1, 'crazy': 1, 'went': 1, 'mountain': 1}
[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3), ('word', 2), ('keeping', 2), ('good', 1), ('knew', 1), ('driving', 1), ('crazy', 1), ('went', 1), ('mountain', 1)]


In [52]:
# 정수 인코딩 시작
# 높은 빈도 수를 가진 word를 1부터 지정
# 높은 빈도 수대로 지정하던 문장의 순서대로 지정하던 사실 상관은 없다
word_to_index = {}
i = 0
for (key, values) in vocab_sorted :
    if values > 1 : # 빈도수가 작은 단어는 제외.
        i = i + 1
        word_to_index[key] = i

print(word_to_index)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7}


In [58]:
vocab_size = 5

# 인덱스가 5 초과인 단어 제거
words_frequency = [word for word, index in word_to_index.items() if index >= vocab_size + 1]

# 해당 단어에 대한 인덱스 정보를 삭제
for w in words_frequency:
    del word_to_index[w]
print(word_to_index)

# Out of vacab 방지, 단어 사전에 단어들이 없을 수도
word_to_index['OOV'] = 0
print(word_to_index)

encoded_sentences = []
for sentence in preprocessed_sentences:
    encoded_sentence = []
    for word in sentence:
        try:
            # 단어 집합에 있는 단어라면 해당 단어의 정수를 리턴.
            encoded_sentence.append(word_to_index[word])
        except KeyError:
            # 만약 단어 집합에 없는 단어라면 'OOV'의 정수를 리턴.
            encoded_sentence.append(word_to_index['OOV'])
    encoded_sentences.append(encoded_sentence)
print(encoded_sentences)

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}
{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 0}
[[1, 5], [1, 0, 5], [1, 3, 5], [0, 2], [2, 4, 3, 2], [3, 2], [1, 4, 0], [1, 4, 0], [1, 4, 2], [0, 0, 3, 2, 0, 1, 0], [1, 0, 3, 0]]


In [59]:
# 원핫 인코딩
def one_hot_encoding(word, word_to_index):
  one_hot_vector = [0]*(len(word_to_index))
  index = word_to_index[word]
  one_hot_vector[index] = 1
  return one_hot_vector

In [63]:
print(one_hot_encoding("barber", word_to_index))
print(one_hot_encoding("secret", word_to_index))

[0, 1, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 0]


### keras version

In [74]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

tokenizer = Tokenizer()
# fit_on_texts: 글자와 숫자 정보 mapping -> 이전에 봤던 딕셔너리 형태
# preprocessed_sentences: 불용어 제거 버전
tokenizer.fit_on_texts(preprocessed_sentences)
print('단어 집합 :',tokenizer.word_index)

단어 집합 : {'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'word': 6, 'keeping': 7, 'good': 8, 'knew': 9, 'driving': 10, 'crazy': 11, 'went': 12, 'mountain': 13}


In [75]:
# 정수 인덱싱: texts_to_sequences
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [81]:
# 13개의 단어는 너무 많으니 단어를 5개로 줄여서 사용
vocab_size = 5
tokenizer = Tokenizer(num_words = vocab_size + 1) # 상위 5개 단어만 사용, 현재 0은 안쓰기 때문에 5까지 하려면 +1
tokenizer.fit_on_texts(preprocessed_sentences)

# 실제 적용 시기
encoded = tokenizer.texts_to_sequences(preprocessed_sentences)
print(encoded)

[[1, 5], [1, 5], [1, 3, 5], [2], [2, 4, 3, 2], [3, 2], [1, 4], [1, 4], [1, 4, 2], [3, 2, 1], [1, 3]]


In [82]:
max_len = max(len(item) for item in encoded)
print('최대 길이 :',max_len)

최대 길이 : 4


In [83]:
import numpy as np

for sentence in encoded:
    while len(sentence) < max_len:
        sentence.append(0)

padded_np = np.array(encoded)
padded_np

array([[1, 5, 0, 0],
       [1, 5, 0, 0],
       [1, 3, 5, 0],
       [2, 0, 0, 0],
       [2, 4, 3, 2],
       [3, 2, 0, 0],
       [1, 4, 0, 0],
       [1, 4, 0, 0],
       [1, 4, 2, 0],
       [3, 2, 1, 0],
       [1, 3, 0, 0]])

In [84]:
# 원핫 인코딩을 할 때 반드시 패딩을 우선적으로 수행할 것!
# 문장 길이를 맞추어 주어야 한다.
one_hot = to_categorical(encoded)
print(one_hot)

[[[0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]]

 [[0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0.]
  [0. 0. 1. 0. 0. 0.]]

 [[0. 0. 0. 1. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0.]
  [1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0.]
  [1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0.]
  [0. 0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0. 0.]
  [0. 0. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0.]
  [1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0.]]]
