In [1]:
#케라스로 RNN구현하기

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN

model=Sequential()
model.add(SimpleRNN(3,input_shape=(2,10)))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [4]:
model=Sequential()
model.add(SimpleRNN(3,batch_input_shape=(8,2,10)))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (8, 3)                    42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [5]:
model=Sequential()
model.add(SimpleRNN(3,batch_input_shape=(8,2,10), return_sequences=True))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_3 (SimpleRNN)    (8, 2, 3)                 42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [6]:
#파이썬으로 RNN구현하기

In [8]:
import numpy as np

timesteps=10
input_dim=4
hidden_units=8

#입력에 해당되는 2D텐서
inputs=np.random.random((timesteps,input_dim))

hidden_state_t= np.zeros((hidden_units,))

print('초기 은닉 상태:', hidden_state_t)

초기 은닉 상태: [0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
Wx= np.random.random((hidden_units,input_dim))
Wh=np.random.random((hidden_units,hidden_units))
b=np.random.random((hidden_units,))

print('가중치 Wx의 크기(shape):', np.shape(Wx))
print('가중치 Wh의 크기(shape):', np.shape(Wh))
print('편향의 크기(shape):', np.shape(b))

가중치 Wx의 크기(shape): (8, 4)
가중치 Wh의 크기(shape): (8, 8)
편향의 크기(shape): (8,)


In [10]:
#RNN층 동작
total_hidden_states=[]

for input_t in inputs:
    output_t=np.tanh(np.dot(Wx,input_t)+ np.dot(Wh,hidden_state_t)+b)
    
    total_hidden_states.append(list(output_t))
    hidden_state_t= output_t
    
total_hidden_states = np.stack(total_hidden_states, axis=0)

print('모든시점의 은닉상태:')
print(total_hidden_states)

모든시점의 은닉상태:
[[0.96476303 0.98432785 0.96712811 0.97826635 0.82825681 0.98389014
  0.98708025 0.76640961]
 [0.99999786 0.9999661  0.9999973  0.99998415 0.99786221 0.9995871
  0.99999344 0.99994014]
 [0.99999827 0.99993598 0.99999592 0.99998188 0.99813437 0.99903812
  0.9999904  0.99990832]
 [0.99999891 0.9999628  0.9999973  0.99998973 0.99907135 0.99942139
  0.99999492 0.99994351]
 [0.99999776 0.99994813 0.99999649 0.99998047 0.99830962 0.99909658
  0.99999213 0.99993743]
 [0.99999785 0.9999642  0.99999549 0.99998652 0.99738387 0.99903357
  0.99999212 0.99992748]
 [0.99999937 0.99997644 0.99999786 0.99999484 0.99903528 0.99966421
  0.9999966  0.999942  ]
 [0.99999127 0.99992055 0.99999521 0.99993768 0.99668102 0.99809256
  0.99998622 0.99994858]
 [0.99999907 0.99998767 0.99999875 0.99999518 0.99916535 0.99979108
  0.99999823 0.99997605]
 [0.99999897 0.99997011 0.9999985  0.9999903  0.99939469 0.99966515
  0.99999695 0.99996695]]


In [11]:
#깊은 순환 신경망
model = Sequential()
model.add(SimpleRNN(hidden_units, input_length=10, input_dim=5, return_sequences=True))
model.add(SimpleRNN(hidden_units, return_sequences=True))


In [13]:
#양방향 순환신경망
from tensorflow.keras.layers import Bidirectional
timesteps=10
input_dim=5

model=Sequential()
model.add(Bidirectional(SimpleRNN(hidden_units, return_sequences=True), input_shape=(timesteps, input_dim)))

In [14]:
model = Sequential()
model.add(Bidirectional(SimpleRNN(hidden_units, return_sequences=True), input_shape=(timesteps, input_dim)))
model.add(Bidirectional(SimpleRNN(hidden_units, return_sequences=True)))
model.add(Bidirectional(SimpleRNN(hidden_units, return_sequences=True)))
model.add(Bidirectional(SimpleRNN(hidden_units, return_sequences=True)))

In [15]:
#케라스에서 GRU
model.add(GRU(hidden_size, input_shape=(timesteps, input_dim)))

NameError: name 'GRU' is not defined

In [16]:
#케라스에서 SimpleRNN과 LTSM이해하기
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN , LSTM, Bidirectional

In [17]:
train_X = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_X))

(4, 5)


In [18]:
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


In [19]:
# SImpleRNN
rnn=SimpleRNN(3)
hidden_state= rnn(train_X)
print('hidden state: {}, shape: {}'.format(hidden_state,hidden_state.shape))

hidden state: [[-0.9980013 -0.9663857 -0.0813536]], shape: (1, 3)


In [20]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_states = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))

hidden states : [[[-0.48502576 -0.87370014 -0.97650576]
  [-0.98270655 -0.9618492  -0.97284746]
  [-0.9874757  -0.8638253  -0.98377   ]
  [-0.9793333   0.659656   -0.3529194 ]]], shape: (1, 4, 3)


In [21]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden states : [[[ 0.99706477  0.94030434 -0.9713305 ]
  [ 0.9980922   0.9560972  -0.96196353]
  [ 0.9931357   0.97797775 -0.9922364 ]
  [ 0.97120494  0.9609152  -0.9938699 ]]], shape: (1, 4, 3)
last hidden state : [[ 0.97120494  0.9609152  -0.9938699 ]], shape: (1, 3)


In [22]:
rnn = SimpleRNN(3, return_sequences=False, return_state=True)
hidden_state, last_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden state : [[ 0.58851355 -0.989359    0.6749512 ]], shape: (1, 3)
last hidden state : [[ 0.58851355 -0.989359    0.6749512 ]], shape: (1, 3)


In [25]:
#LSTM 
lstm=LSTM(3,return_sequences=False, return_state=True)
hidden_state,last_state,last_cell_state = lstm(train_X)

print('hidden state:{}, hape: {}'.format(hidden_state, hidden_state.shape))
print('last hidden state:{}, shape:{}'.format(last_state, last_state.shape))
print('last cell state: {}, shape: {}'.format(last_cell_state,last_cell_state.shape))

hidden state:[[-0.21902545 -0.08918695  0.13374394]], hape: (1, 3)
last hidden state:[[-0.21902545 -0.08918695  0.13374394]], shape:(1, 3)
last cell state: [[-0.5449333  -0.40312988  0.46886265]], shape: (1, 3)


In [26]:
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_states, last_hidden_state, last_cell_state = lstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_hidden_state, last_hidden_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))


hidden states : [[[-0.28946584 -0.35559174  0.318317  ]
  [-0.28974527 -0.2723003   0.34903792]
  [-0.24002561 -0.45638454  0.40264106]
  [-0.3012215  -0.3124423   0.2639909 ]]], shape: (1, 4, 3)
last hidden state : [[-0.3012215 -0.3124423  0.2639909]], shape: (1, 3)
last cell state : [[-0.51159006 -1.6248031   0.87611765]], shape: (1, 3)


In [28]:
#Bidirectional
k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)


In [30]:
bilstm = Bidirectional(LSTM(3, return_sequences=False, return_state=True, \
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))


hidden states : [[0.6303138 0.6303138 0.6303138 0.7038734 0.7038734 0.7038734]], shape: (1, 6)
forward state : [[0.6303138 0.6303138 0.6303138]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


In [31]:
bilstm = Bidirectional(LSTM(3, return_sequences=True, return_state=True, \
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)


In [32]:
print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[[0.35906473 0.35906473 0.35906473 0.7038734  0.7038734  0.7038734 ]
  [0.55111325 0.55111325 0.55111325 0.58863586 0.58863586 0.58863586]
  [0.59115744 0.59115744 0.59115744 0.3951699  0.3951699  0.3951699 ]
  [0.6303138  0.6303138  0.6303138  0.21942244 0.21942244 0.21942244]]], shape: (1, 4, 6)
forward state : [[0.6303138 0.6303138 0.6303138]], shape: (1, 3)
backward state : [[0.7038734 0.7038734 0.7038734]], shape: (1, 3)


In [33]:
#06 RNN을 이용한 텍스트 생성

In [35]:
#데이터에 대한 이해와 전처리
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [36]:
text = """경마장에 있는 말이 뛰고 있다\n
그의 말이 법이다\n
가는 말이 고와야 오는 말이 곱다\n"""

In [37]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
vocab_size=len(tokenizer.word_index)+1
print('단어 집합의 크기: %d' %vocab_size)

단어 집합의 크기: 12


In [38]:
print(tokenizer.word_index)

{'말이': 1, '경마장에': 2, '있는': 3, '뛰고': 4, '있다': 5, '그의': 6, '법이다': 7, '가는': 8, '고와야': 9, '오는': 10, '곱다': 11}


In [39]:
sequences= list()
for line in text.split('\n'):
    encoded = tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(encoded)):
        sequence=encoded[:i+1]
        sequences.append(sequence)
        
print('학습에 사용할 샘플의 개수: %d' %len(sequences))

학습에 사용할 샘플의 개수: 11


In [41]:
print(sequences)

[[2, 3], [2, 3, 1], [2, 3, 1, 4], [2, 3, 1, 4, 5], [6, 1], [6, 1, 7], [8, 1], [8, 1, 9], [8, 1, 9, 10], [8, 1, 9, 10, 1], [8, 1, 9, 10, 1, 11]]


In [43]:
max_len=max(len(I) for I in sequences)
print('샘플의 최대 길이: {}'.format(max_len))

샘플의 최대 길이: 6


In [44]:
sequences= pad_sequences(sequences,maxlen=max_len, padding='pre')

In [45]:
print(sequences)

[[ 0  0  0  0  2  3]
 [ 0  0  0  2  3  1]
 [ 0  0  2  3  1  4]
 [ 0  2  3  1  4  5]
 [ 0  0  0  0  6  1]
 [ 0  0  0  6  1  7]
 [ 0  0  0  0  8  1]
 [ 0  0  0  8  1  9]
 [ 0  0  8  1  9 10]
 [ 0  8  1  9 10  1]
 [ 8  1  9 10  1 11]]


In [46]:
sequences=np.array(sequences)
X=sequences[:,:-1]
y=sequences[:,-1]

In [47]:
print(X)

[[ 0  0  0  0  2]
 [ 0  0  0  2  3]
 [ 0  0  2  3  1]
 [ 0  2  3  1  4]
 [ 0  0  0  0  6]
 [ 0  0  0  6  1]
 [ 0  0  0  0  8]
 [ 0  0  0  8  1]
 [ 0  0  8  1  9]
 [ 0  8  1  9 10]
 [ 8  1  9 10  1]]


In [48]:
print(y)

[ 3  1  4  5  1  7  1  9 10  1 11]


In [49]:
y=to_categorical(y,num_classes=vocab_size)

In [50]:
print(y)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [51]:
#2모델 설계하기

In [52]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Dense,SimpleRNN

In [55]:
embedding_dim=10
hidden_units=32

model=Sequential()
model.add(Embedding(vocab_size,embedding_dim))
model.add(SimpleRNN(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X,y,epochs=200,verbose=2)

Epoch 1/200
1/1 - 1s - loss: 2.4527 - accuracy: 0.0909 - 1s/epoch - 1s/step
Epoch 2/200
1/1 - 0s - loss: 2.4386 - accuracy: 0.1818 - 8ms/epoch - 8ms/step
Epoch 3/200
1/1 - 0s - loss: 2.4243 - accuracy: 0.2727 - 6ms/epoch - 6ms/step
Epoch 4/200
1/1 - 0s - loss: 2.4098 - accuracy: 0.2727 - 7ms/epoch - 7ms/step
Epoch 5/200
1/1 - 0s - loss: 2.3949 - accuracy: 0.3636 - 7ms/epoch - 7ms/step
Epoch 6/200
1/1 - 0s - loss: 2.3795 - accuracy: 0.3636 - 6ms/epoch - 6ms/step
Epoch 7/200
1/1 - 0s - loss: 2.3637 - accuracy: 0.4545 - 8ms/epoch - 8ms/step
Epoch 8/200
1/1 - 0s - loss: 2.3472 - accuracy: 0.4545 - 6ms/epoch - 6ms/step
Epoch 9/200
1/1 - 0s - loss: 2.3301 - accuracy: 0.4545 - 10ms/epoch - 10ms/step
Epoch 10/200
1/1 - 0s - loss: 2.3122 - accuracy: 0.4545 - 7ms/epoch - 7ms/step
Epoch 11/200
1/1 - 0s - loss: 2.2936 - accuracy: 0.3636 - 6ms/epoch - 6ms/step
Epoch 12/200
1/1 - 0s - loss: 2.2740 - accuracy: 0.3636 - 7ms/epoch - 7ms/step
Epoch 13/200
1/1 - 0s - loss: 2.2536 - accuracy: 0.3636 - 6ms

Epoch 105/200
1/1 - 0s - loss: 0.6159 - accuracy: 0.8182 - 4ms/epoch - 4ms/step
Epoch 106/200
1/1 - 0s - loss: 0.6059 - accuracy: 0.8182 - 6ms/epoch - 6ms/step
Epoch 107/200
1/1 - 0s - loss: 0.5961 - accuracy: 0.8182 - 5ms/epoch - 5ms/step
Epoch 108/200
1/1 - 0s - loss: 0.5865 - accuracy: 0.8182 - 5ms/epoch - 5ms/step
Epoch 109/200
1/1 - 0s - loss: 0.5771 - accuracy: 0.8182 - 5ms/epoch - 5ms/step
Epoch 110/200
1/1 - 0s - loss: 0.5678 - accuracy: 0.8182 - 4ms/epoch - 4ms/step
Epoch 111/200
1/1 - 0s - loss: 0.5587 - accuracy: 0.8182 - 5ms/epoch - 5ms/step
Epoch 112/200
1/1 - 0s - loss: 0.5498 - accuracy: 0.8182 - 3ms/epoch - 3ms/step
Epoch 113/200
1/1 - 0s - loss: 0.5410 - accuracy: 0.8182 - 5ms/epoch - 5ms/step
Epoch 114/200
1/1 - 0s - loss: 0.5324 - accuracy: 0.8182 - 4ms/epoch - 4ms/step
Epoch 115/200
1/1 - 0s - loss: 0.5239 - accuracy: 0.8182 - 4ms/epoch - 4ms/step
Epoch 116/200
1/1 - 0s - loss: 0.5156 - accuracy: 0.8182 - 3ms/epoch - 3ms/step
Epoch 117/200
1/1 - 0s - loss: 0.5075 - 

In [68]:
def sentence_generation(model,tokenizer,current_word,n):
    init_word=current_word
    sentence=''
    for _ in range(n):
        encoded =tokenizer.texts_to_sequences([current_word])[0]
        encoded=pad_sequences([encoded],maxlen=5, padding='pre')
        
        result=model.predict(encoded,verbose=0)
        result= np.argmax(result, axis=1)
        
        for word, index in tokenizer.word_index.items():
            if index ==result:
                break
                
        current_word = current_word+ ' ' + word
        
        sentence= sentence + ' '+ word
        
        
    sentence= init_word+sentence
    return sentence
        

In [69]:
print(sentence_generation(model,tokenizer,'경마장에', 4))

경마장에 있는 말이 뛰고 있다


In [70]:
print(sentence_generation(model,tokenizer,'그의',2))

그의 말이 법이다


In [71]:
print(sentence_generation(model,tokenizer,'가는', 5))

가는 말이 고와야 오는 말이 곱다


In [74]:
import pandas as pd
import numpy as np
from string import punctuation

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [76]:
df = pd.read_csv('ArticlesApril2018.csv')
df.head()

articleID  articleWordCount  \
0  5adf6684068401528a2aa69b               781   
1  5adf653f068401528a2aa697               656   
2  5adf4626068401528a2aa628              2427   
3  5adf40d2068401528a2aa619               626   
4  5adf3d64068401528a2aa60f               815   

                                      byline documentType  \
0                             By JOHN BRANCH      article   
1                           By LISA FRIEDMAN      article   
2                              By PETE WELLS      article   
3  By JULIE HIRSCHFELD DAVIS and PETER BAKER      article   
4             By IAN AUSTEN and DAN BILEFSKY      article   

                                            headline  \
0  Former N.F.L. Cheerleaders’ Settlement Offer: ...   
1  E.P.A. to Unveil a New Rule. Its Effect: Less ...   
2                            The New Noma, Explained   
3                                            Unknown   
4                                            Unknown   

                                            keywords  multimedia     newDesk  \
0  ['Workplace Hazards and Violations', 'Football...          68      Sports   
1  ['Environmental Protection Agency', 'Pruitt, S...          68     Climate   
2  ['Restaurants', 'Noma (Copenhagen, Restaurant)...          66      Dining   
3  ['Macron, Emmanuel (1977- )', 'Trump, Donald J...          68  Washington   
4  ['Toronto, Ontario, Attack (April, 2018)', 'Mu...          68     Foreign   

   printPage              pubDate   sectionName  \
0          0  2018-04-24 17:16:49  Pro Football   
1          0  2018-04-24 17:11:21       Unknown   
2          0  2018-04-24 14:58:44       Unknown   
3          0  2018-04-24 14:35:57        Europe   
4          0  2018-04-24 14:21:21        Canada   

                                             snippet              source  \
0  “I understand that they could meet with us, pa...  The New York Times   
1  The agency plans to publish a new regulation T...  The New York Times   
2  What’s it like to eat at the second incarnatio...  The New York Times   
3  President Trump welcomed President Emmanuel Ma...  The New York Times   
4  Alek Minassian, 25, a resident of Toronto’s Ri...  The New York Times   

  typeOfMaterial                                             webURL  
0           News  https://www.nytimes.com/2018/04/24/sports/foot...  
1           News  https://www.nytimes.com/2018/04/24/climate/epa...  
2           News  https://www.nytimes.com/2018/04/24/dining/noma...  
3           News  https://www.nytimes.com/2018/04/24/world/europ...  
4           News  https://www.nytimes.com/2018/04/24/world/canad...

In [77]:
print('열의 개수:', len(df.columns))
print(df.columns)

열의 개수: 15
Index(['articleID', 'articleWordCount', 'byline', 'documentType', 'headline',
       'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')


In [79]:
print(df['headline'].isnull().values.any())

False


In [82]:
headline=[]
headline.extend(list(df.headline.values))
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'Unknown',
 'Unknown']

In [83]:
print('총 샘플의 개수:{}'.format(len(headline)))

총 샘플의 개수:1324


In [84]:
headline=[word for word in headline if word  !='Unknown']
print('노이즈 값 제거 후 샘플의 개수: {}'.format(len(headline)))

노이즈 값 제거 후 샘플의 개수: 1214


In [85]:
headline[:5]

['Former N.F.L. Cheerleaders’ Settlement Offer: $1 and a Meeting With Goodell',
 'E.P.A. to Unveil a New Rule. Its Effect: Less Science in Policymaking.',
 'The New Noma, Explained',
 'How a Bag of Texas Dirt  Became a Times Tradition',
 'Is School a Place for Self-Expression?']

In [89]:
def repreprocessing(raw_sentence):
    preprocesseed_sentence= raw_sentence.encode('utf8').decode('ascii','ignore')
    return ''.join(word for word in preprocesseed_sentence if word not in punctuation).lower()

preprocessed_headline =[repreprocessing(x) for x in headline]
preprocessed_headline[:5]

['former nfl cheerleaders settlement offer 1 and a meeting with goodell',
 'epa to unveil a new rule its effect less science in policymaking',
 'the new noma explained',
 'how a bag of texas dirt  became a times tradition',
 'is school a place for selfexpression']

In [91]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(preprocessed_headline)
vocab_size= len(tokenizer.word_index)+1
print('단어 집합의 크기: %d' % vocab_size)

단어 집합의 크기: 3494


In [95]:
sequences=list()
for sentence in preprocessed_headline:
    
    encoded = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1,len(encoded)):
        sequence= encoded[:i+1]
        sequences.append(sequence)
        
sequences[:11]

[[99, 269],
 [99, 269, 371],
 [99, 269, 371, 1115],
 [99, 269, 371, 1115, 582],
 [99, 269, 371, 1115, 582, 52],
 [99, 269, 371, 1115, 582, 52, 7],
 [99, 269, 371, 1115, 582, 52, 7, 2],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10],
 [99, 269, 371, 1115, 582, 52, 7, 2, 372, 10, 1116],
 [100, 3]]

In [97]:
index_to_word = {}
for key, value in tokenizer.word_index.items(): # 인덱스를 단어로 바꾸기 위해 index_to_word를 생성
    index_to_word[value] = key

print('빈도수 상위 582번 단어 : {}'.format(index_to_word[582]))


빈도수 상위 582번 단어 : offer


In [98]:
max_len = max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 24


In [99]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences[:3])

[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0   99  269]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0   99  269  371]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0   99  269  371 1115]]


In [100]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]

In [101]:
print(X[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0  99]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0  99 269]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0  99 269 371]]


In [102]:
print(y[:3])

[ 269  371 1115]


In [103]:
y = to_categorical(y, num_classes=vocab_size)

In [104]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [105]:
embedding_dim = 10
hidden_units = 128

model = Sequential()
model.add(Embedding(vocab_size, embedding_dim))
model.add(LSTM(hidden_units))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=200, verbose=2)

Epoch 1/200
244/244 - 6s - loss: 7.6290 - accuracy: 0.0299 - 6s/epoch - 25ms/step
Epoch 2/200
244/244 - 4s - loss: 7.1144 - accuracy: 0.0282 - 4s/epoch - 15ms/step
Epoch 3/200
244/244 - 3s - loss: 6.9809 - accuracy: 0.0328 - 3s/epoch - 14ms/step
Epoch 4/200
244/244 - 3s - loss: 6.8570 - accuracy: 0.0397 - 3s/epoch - 14ms/step
Epoch 5/200
244/244 - 4s - loss: 6.7068 - accuracy: 0.0442 - 4s/epoch - 15ms/step
Epoch 6/200
244/244 - 4s - loss: 6.5333 - accuracy: 0.0477 - 4s/epoch - 16ms/step
Epoch 7/200
244/244 - 4s - loss: 6.3459 - accuracy: 0.0497 - 4s/epoch - 16ms/step
Epoch 8/200
244/244 - 4s - loss: 6.1506 - accuracy: 0.0584 - 4s/epoch - 16ms/step
Epoch 9/200
244/244 - 4s - loss: 5.9649 - accuracy: 0.0598 - 4s/epoch - 14ms/step
Epoch 10/200
244/244 - 3s - loss: 5.7851 - accuracy: 0.0616 - 3s/epoch - 14ms/step
Epoch 11/200
244/244 - 3s - loss: 5.6100 - accuracy: 0.0677 - 3s/epoch - 13ms/step
Epoch 12/200
244/244 - 3s - loss: 5.4466 - accuracy: 0.0761 - 3s/epoch - 14ms/step
Epoch 13/200


Epoch 100/200
244/244 - 4s - loss: 0.6737 - accuracy: 0.8662 - 4s/epoch - 16ms/step
Epoch 101/200
244/244 - 4s - loss: 0.6587 - accuracy: 0.8693 - 4s/epoch - 16ms/step
Epoch 102/200
244/244 - 4s - loss: 0.6468 - accuracy: 0.8733 - 4s/epoch - 16ms/step
Epoch 103/200
244/244 - 4s - loss: 0.6323 - accuracy: 0.8747 - 4s/epoch - 16ms/step
Epoch 104/200
244/244 - 4s - loss: 0.6184 - accuracy: 0.8772 - 4s/epoch - 15ms/step
Epoch 105/200
244/244 - 4s - loss: 0.6057 - accuracy: 0.8775 - 4s/epoch - 16ms/step
Epoch 106/200
244/244 - 4s - loss: 0.5943 - accuracy: 0.8807 - 4s/epoch - 16ms/step
Epoch 107/200
244/244 - 4s - loss: 0.5815 - accuracy: 0.8811 - 4s/epoch - 16ms/step
Epoch 108/200
244/244 - 4s - loss: 0.5706 - accuracy: 0.8862 - 4s/epoch - 18ms/step
Epoch 109/200
244/244 - 4s - loss: 0.5593 - accuracy: 0.8861 - 4s/epoch - 18ms/step
Epoch 110/200
244/244 - 4s - loss: 0.5487 - accuracy: 0.8894 - 4s/epoch - 17ms/step
Epoch 111/200
244/244 - 4s - loss: 0.5377 - accuracy: 0.8902 - 4s/epoch - 18

KeyboardInterrupt: 

In [106]:
def sentence_generation(model, tokenizer, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word
    sentence = ''

    # n번 반복
    for _ in range(n):
        encoded = tokenizer.texts_to_sequences([current_word])[0]
        encoded = pad_sequences([encoded], maxlen=max_len-1, padding='pre')

        # 입력한 X(현재 단어)에 대해서 y를 예측하고 y(예측한 단어)를 result에 저장.
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis=1)

        for word, index in tokenizer.word_index.items(): 
            # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
            if index == result:
                break

        # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        current_word = current_word + ' '  + word

        # 예측 단어를 문장에 저장
        sentence = sentence + ' ' + word

    sentence = init_word + sentence
    return sentence

In [107]:
print(sentence_generation(model, tokenizer, 'i', 10))


i disapprove of school vouchers can i still apply for them


In [108]:
print(sentence_generation(model, tokenizer, 'how', 10))

how a landlord fit for dr king client over say just


In [109]:
import numpy as np
import urllib.request
from tensorflow.keras.utils import to_categorical

# 데이터 로드
urllib.request.urlretrieve("http://www.gutenberg.org/files/11/11-0.txt", filename="11-0.txt")

f = open('11-0.txt', 'rb')
sentences = []
for sentence in f: # 데이터로부터 한 줄씩 읽는다.
    sentence = sentence.strip() # strip()을 통해 \r, \n을 제거한다.
    sentence = sentence.lower() # 소문자화.
    sentence = sentence.decode('ascii', 'ignore') # \xe2\x80\x99 등과 같은 바이트 열 제거
    if len(sentence) > 0:
        sentences.append(sentence)
f.close()


In [110]:
sentences[:5]

['the project gutenberg ebook of alices adventures in wonderland, by lewis carroll',
 'this ebook is for the use of anyone anywhere in the united states and',
 'most other parts of the world at no cost and with almost no restrictions',
 'whatsoever. you may copy it, give it away or re-use it under the terms',
 'of the project gutenberg license included with this ebook or online at']

In [111]:
total_data=' '.join(sentences)
print('문자열의 길이 또는 총 문자의 개수: %d' %len(total_data))

문자열의 길이 또는 총 문자의 개수: 159484


In [112]:
print(total_data[:200])

the project gutenberg ebook of alices adventures in wonderland, by lewis carroll this ebook is for the use of anyone anywhere in the united states and most other parts of the world at no cost and with


In [113]:
char_vocab= sorted(list(set(total_data)))
vocab_size=len(char_vocab)
print('문자 집합의 크기: {}'.format(vocab_size))

문자 집합의 크기: 56


In [114]:
# 문자에 고유한 정수 부여
char_to_index = dict((char, index) for index, char in enumerate(char_vocab))
print('문자 집합 :',char_to_index)

문자 집합 : {' ': 0, '!': 1, '"': 2, '#': 3, '$': 4, '%': 5, "'": 6, '(': 7, ')': 8, '*': 9, ',': 10, '-': 11, '.': 12, '/': 13, '0': 14, '1': 15, '2': 16, '3': 17, '4': 18, '5': 19, '6': 20, '7': 21, '8': 22, '9': 23, ':': 24, ';': 25, '?': 26, '[': 27, ']': 28, '_': 29, 'a': 30, 'b': 31, 'c': 32, 'd': 33, 'e': 34, 'f': 35, 'g': 36, 'h': 37, 'i': 38, 'j': 39, 'k': 40, 'l': 41, 'm': 42, 'n': 43, 'o': 44, 'p': 45, 'q': 46, 'r': 47, 's': 48, 't': 49, 'u': 50, 'v': 51, 'w': 52, 'x': 53, 'y': 54, 'z': 55}


In [115]:
index_to_char = {}
for key, value in char_to_index.items():
    index_to_char[value] = key

In [116]:
# appl (입력 시퀀스) -> pple (예측해야하는 시퀀스)
train_X = 'appl'
train_y = 'pple'

In [117]:
seq_length = 60

# 문자열의 길이를 seq_length로 나누면 전처리 후 생겨날 샘플 수
n_samples = int(np.floor((len(total_data) - 1) / seq_length))
print ('샘플의 수 : {}'.format(n_samples))

샘플의 수 : 2658


In [118]:
train_X = []
train_y = []

for i in range(n_samples):
    # 0:60 -> 60:120 -> 120:180로 loop를 돌면서 문장 샘플을 1개씩 pick.
    X_sample = total_data[i * seq_length: (i + 1) * seq_length]

    # 정수 인코딩
    X_encoded = [char_to_index[c] for c in X_sample]
    train_X.append(X_encoded)

    # 오른쪽으로 1칸 쉬프트
    y_sample = total_data[i * seq_length + 1: (i + 1) * seq_length + 1]
    y_encoded = [char_to_index[c] for c in y_sample]
    train_y.append(y_encoded)

In [119]:
print('X 데이터의 첫번째 샘플 :',train_X[0])
print('y 데이터의 첫번째 샘플 :',train_y[0])
print('-'*50)
print('X 데이터의 첫번째 샘플 디코딩 :',[index_to_char[i] for i in train_X[0]])
print('y 데이터의 첫번째 샘플 디코딩 :',[index_to_char[i] for i in train_y[0]])

X 데이터의 첫번째 샘플 : [49, 37, 34, 0, 45, 47, 44, 39, 34, 32, 49, 0, 36, 50, 49, 34, 43, 31, 34, 47, 36, 0, 34, 31, 44, 44, 40, 0, 44, 35, 0, 30, 41, 38, 32, 34, 48, 0, 30, 33, 51, 34, 43, 49, 50, 47, 34, 48, 0, 38, 43, 0, 52, 44, 43, 33, 34, 47, 41, 30]
y 데이터의 첫번째 샘플 : [37, 34, 0, 45, 47, 44, 39, 34, 32, 49, 0, 36, 50, 49, 34, 43, 31, 34, 47, 36, 0, 34, 31, 44, 44, 40, 0, 44, 35, 0, 30, 41, 38, 32, 34, 48, 0, 30, 33, 51, 34, 43, 49, 50, 47, 34, 48, 0, 38, 43, 0, 52, 44, 43, 33, 34, 47, 41, 30, 43]
--------------------------------------------------
X 데이터의 첫번째 샘플 디코딩 : ['t', 'h', 'e', ' ', 'p', 'r', 'o', 'j', 'e', 'c', 't', ' ', 'g', 'u', 't', 'e', 'n', 'b', 'e', 'r', 'g', ' ', 'e', 'b', 'o', 'o', 'k', ' ', 'o', 'f', ' ', 'a', 'l', 'i', 'c', 'e', 's', ' ', 'a', 'd', 'v', 'e', 'n', 't', 'u', 'r', 'e', 's', ' ', 'i', 'n', ' ', 'w', 'o', 'n', 'd', 'e', 'r', 'l', 'a']
y 데이터의 첫번째 샘플 디코딩 : ['h', 'e', ' ', 'p', 'r', 'o', 'j', 'e', 'c', 't', ' ', 'g', 'u', 't', 'e', 'n', 'b', 'e', 'r', 'g', ' ', 'e',

In [120]:
print(train_X[1])

[43, 33, 10, 0, 31, 54, 0, 41, 34, 52, 38, 48, 0, 32, 30, 47, 47, 44, 41, 41, 0, 49, 37, 38, 48, 0, 34, 31, 44, 44, 40, 0, 38, 48, 0, 35, 44, 47, 0, 49, 37, 34, 0, 50, 48, 34, 0, 44, 35, 0, 30, 43, 54, 44, 43, 34, 0, 30, 43, 54]


In [121]:
print(train_y[1])

[33, 10, 0, 31, 54, 0, 41, 34, 52, 38, 48, 0, 32, 30, 47, 47, 44, 41, 41, 0, 49, 37, 38, 48, 0, 34, 31, 44, 44, 40, 0, 38, 48, 0, 35, 44, 47, 0, 49, 37, 34, 0, 50, 48, 34, 0, 44, 35, 0, 30, 43, 54, 44, 43, 34, 0, 30, 43, 54, 52]


In [122]:
train_X = to_categorical(train_X)
train_y = to_categorical(train_y)

print('train_X의 크기(shape) : {}'.format(train_X.shape)) # 원-핫 인코딩
print('train_y의 크기(shape) : {}'.format(train_y.shape)) # 원-핫 인코딩

train_X의 크기(shape) : (2658, 60, 56)
train_y의 크기(shape) : (2658, 60, 56)


In [125]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, TimeDistributed

hidden_units = 256

model = Sequential()
model.add(LSTM(hidden_units, input_shape=(None, train_X.shape[2]), return_sequences=True))
model.add(LSTM(hidden_units, return_sequences=True))
model.add(TimeDistributed(Dense(vocab_size, activation='softmax')))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(train_X, train_y, epochs=80, verbose=2)


Epoch 1/80
84/84 - 24s - loss: 3.0675 - accuracy: 0.1832 - 24s/epoch - 286ms/step
Epoch 2/80
84/84 - 22s - loss: 2.7729 - accuracy: 0.2384 - 22s/epoch - 263ms/step
Epoch 3/80
84/84 - 25s - loss: 2.4230 - accuracy: 0.3208 - 25s/epoch - 300ms/step
Epoch 4/80
84/84 - 24s - loss: 2.2756 - accuracy: 0.3532 - 24s/epoch - 287ms/step
Epoch 5/80
84/84 - 24s - loss: 2.1757 - accuracy: 0.3777 - 24s/epoch - 283ms/step
Epoch 6/80
84/84 - 24s - loss: 2.0977 - accuracy: 0.3967 - 24s/epoch - 290ms/step
Epoch 7/80
84/84 - 26s - loss: 2.0375 - accuracy: 0.4123 - 26s/epoch - 304ms/step
Epoch 8/80


KeyboardInterrupt: 

In [126]:
def sentence_generation(model, length):
    # 문자에 대한 랜덤한 정수 생성
    ix = [np.random.randint(vocab_size)]

    # 랜덤한 정수로부터 맵핑되는 문자 생성
    y_char = [index_to_char[ix[-1]]]
    print(ix[-1],'번 문자',y_char[-1],'로 예측을 시작!')

    # (1, length, 55) 크기의 X 생성. 즉, LSTM의 입력 시퀀스 생성
    X = np.zeros((1, length, vocab_size))

    for i in range(length):
        # X[0][i][예측한 문자의 인덱스] = 1, 즉, 예측 문자를 다음 입력 시퀀스에 추가
        X[0][i][ix[-1]] = 1
        print(index_to_char[ix[-1]], end="")
        ix = np.argmax(model.predict(X[:, :i+1, :])[0], 1)
        y_char.append(index_to_char[ix[-1]])
    return ('').join(y_char)


In [127]:
result = sentence_generation(model, 100)
print(result)


40 번 문자 k 로 예측을 시작!
1/1 [==============================] - 0s 64ms/step
k the said the said the said the said the said the said the said the said the said the said the said 


In [128]:
import numpy as np
from tensorflow.keras.utils import to_categorical

In [129]:
raw_text = '''
I get on with life as a programmer,
I like to contemplate beer.
But when I start to daydream,
My mind turns straight to wine.

Do I love wine more than beer?

I like to use words about beer.
But when I stop my talking,
My mind turns straight to wine.

I hate bugs and errors.
But I just think back to wine,
And I'm happy once again.

I like to hang out with programming and deep learning.
But when left alone,
My mind turns straight to wine.
'''

In [130]:
tokens = raw_text.split()
raw_text = ' '.join(tokens)
print(raw_text)

I get on with life as a programmer, I like to contemplate beer. But when I start to daydream, My mind turns straight to wine. Do I love wine more than beer? I like to use words about beer. But when I stop my talking, My mind turns straight to wine. I hate bugs and errors. But I just think back to wine, And I'm happy once again. I like to hang out with programming and deep learning. But when left alone, My mind turns straight to wine.


In [131]:
# 중복을 제거한 문자 집합 생성
char_vocab = sorted(list(set(raw_text)))
vocab_size = len(char_vocab)
print('문자 집합 :',char_vocab)
print ('문자 집합의 크기 : {}'.format(vocab_size))

문자 집합 : [' ', "'", ',', '.', '?', 'A', 'B', 'D', 'I', 'M', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'r', 's', 't', 'u', 'v', 'w', 'y']
문자 집합의 크기 : 33


In [132]:
char_to_index = dict((char, index) for index, char in enumerate(char_vocab)) # 문자에 고유한 정수 인덱스 부여
print(char_to_index)


{' ': 0, "'": 1, ',': 2, '.': 3, '?': 4, 'A': 5, 'B': 6, 'D': 7, 'I': 8, 'M': 9, 'a': 10, 'b': 11, 'c': 12, 'd': 13, 'e': 14, 'f': 15, 'g': 16, 'h': 17, 'i': 18, 'j': 19, 'k': 20, 'l': 21, 'm': 22, 'n': 23, 'o': 24, 'p': 25, 'r': 26, 's': 27, 't': 28, 'u': 29, 'v': 30, 'w': 31, 'y': 32}


In [133]:
length = 11
sequences = []
for i in range(length, len(raw_text)):
    seq = raw_text[i-length:i] # 길이 11의 문자열을 지속적으로 만든다.
    sequences.append(seq)
print('총 훈련 샘플의 수: %d' % len(sequences))


총 훈련 샘플의 수: 426


In [134]:
sequences[:10]


['I get on wi',
 ' get on wit',
 'get on with',
 'et on with ',
 't on with l',
 ' on with li',
 'on with lif',
 'n with life',
 ' with life ',
 'with life a']

In [135]:
encoded_sequences = []
for sequence in sequences: # 전체 데이터에서 문장 샘플을 1개씩 꺼낸다.
    encoded_sequence = [char_to_index[char] for char in sequence] # 문장 샘플에서 각 문자에 대해서 정수 인코딩을 수행.
    encoded_sequences.append(encoded_sequence)

In [136]:
encoded_sequences[:5]

[[8, 0, 16, 14, 28, 0, 24, 23, 0, 31, 18],
 [0, 16, 14, 28, 0, 24, 23, 0, 31, 18, 28],
 [16, 14, 28, 0, 24, 23, 0, 31, 18, 28, 17],
 [14, 28, 0, 24, 23, 0, 31, 18, 28, 17, 0],
 [28, 0, 24, 23, 0, 31, 18, 28, 17, 0, 21]]

In [137]:
encoded_sequences = np.array(encoded_sequences)

# 맨 마지막 위치의 문자를 분리
X_data = encoded_sequences[:,:-1]
# 맨 마지막 위치의 문자를 저장
y_data = encoded_sequences[:,-1]

In [138]:
print(X_data[:5])
print(y_data[:5])

[[ 8  0 16 14 28  0 24 23  0 31]
 [ 0 16 14 28  0 24 23  0 31 18]
 [16 14 28  0 24 23  0 31 18 28]
 [14 28  0 24 23  0 31 18 28 17]
 [28  0 24 23  0 31 18 28 17  0]]
[18 28 17  0 21]


In [139]:
# 원-핫 인코딩
X_data_one_hot = [to_categorical(encoded, num_classes=vocab_size) for encoded in X_data]
X_data_one_hot = np.array(X_data_one_hot)
y_data_one_hot = to_categorical(y_data, num_classes=vocab_size)

In [140]:
print(X_data_one_hot.shape)

(426, 10, 33)


In [141]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.preprocessing.sequence import pad_sequences

hidden_units = 64

model = Sequential()
model.add(LSTM(hidden_units, input_shape=(X_data_one_hot.shape[1], X_data_one_hot.shape[2])))
model.add(Dense(vocab_size, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_data_one_hot, y_data_one_hot, epochs=100, verbose=2)

Epoch 1/100
14/14 - 2s - loss: 3.4673 - accuracy: 0.1432 - 2s/epoch - 139ms/step
Epoch 2/100
14/14 - 0s - loss: 3.3698 - accuracy: 0.1972 - 139ms/epoch - 10ms/step
Epoch 3/100
14/14 - 0s - loss: 3.1327 - accuracy: 0.1972 - 123ms/epoch - 9ms/step
Epoch 4/100
14/14 - 0s - loss: 3.0024 - accuracy: 0.1972 - 122ms/epoch - 9ms/step
Epoch 5/100
14/14 - 0s - loss: 2.9640 - accuracy: 0.1972 - 116ms/epoch - 8ms/step
Epoch 6/100
14/14 - 0s - loss: 2.9393 - accuracy: 0.1972 - 88ms/epoch - 6ms/step
Epoch 7/100
14/14 - 0s - loss: 2.9107 - accuracy: 0.1972 - 92ms/epoch - 7ms/step
Epoch 8/100
14/14 - 0s - loss: 2.8901 - accuracy: 0.1972 - 120ms/epoch - 9ms/step
Epoch 9/100
14/14 - 0s - loss: 2.8641 - accuracy: 0.1972 - 122ms/epoch - 9ms/step
Epoch 10/100
14/14 - 0s - loss: 2.8309 - accuracy: 0.1972 - 92ms/epoch - 7ms/step
Epoch 11/100
14/14 - 0s - loss: 2.8029 - accuracy: 0.1972 - 122ms/epoch - 9ms/step
Epoch 12/100
14/14 - 0s - loss: 2.7715 - accuracy: 0.2066 - 144ms/epoch - 10ms/step
Epoch 13/100
14

Epoch 100/100
14/14 - 0s - loss: 0.2801 - accuracy: 0.9742 - 134ms/epoch - 10ms/step


In [142]:
def sentence_generation(model, char_to_index, seq_length, seed_text, n):

    # 초기 시퀀스
    init_text = seed_text
    sentence = ''

    # 다음 문자 예측은 총 n번만 반복.
    for _ in range(n):
        encoded = [char_to_index[char] for char in seed_text] # 현재 시퀀스에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=seq_length, padding='pre') # 데이터에 대한 패딩
        encoded = to_categorical(encoded, num_classes=len(char_to_index))

        # 입력한 X(현재 시퀀스)에 대해서 y를 예측하고 y(예측한 문자)를 result에 저장.
        result = model.predict(encoded, verbose=0)
        result = np.argmax(result, axis=1)

        for char, index in char_to_index.items():
            if index == result:
                break

        # 현재 시퀀스 + 예측 문자를 현재 시퀀스로 변경
        seed_text = seed_text + char

        # 예측 문자를 문장에 저장
        sentence = sentence + char

    # n번의 다음 문자 예측이 끝나면 최종 완성된 문장을 리턴.
    sentence = init_text + sentence
    return sentence


In [143]:
print(sentence_generation(model, char_to_index, 10, 'I get on w', 80))


I get on with life as a programmer, I like to hang out wihh sfr arsr t tut horrprmmm, ndgr
